version: '3'

services:
  redis-node-1:
    image: redis:alpine
    network_mode: "host"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 46379

  redis-node-2:
    image: redis:alpine
    network_mode: "host"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 46380

  redis-node-3:
    image: redis:alpine
    network_mode: "host"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 46381

  redis-node-4:
    image: redis:alpine
    network_mode: "host"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 46382

  redis-node-5:
    image: redis:alpine
    network_mode: "host"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 46383

  redis-node-6:
    image: redis:alpine
    network_mode: "host"
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 46384
